### ISSUE TITLE
DEBUGGING ISSUE

### ISSUE THREAD

**Issue by ThabisoM-crtl** [Dannark/Android-Launcher-for-VSCode#3]
Issue Type: <b>Bug</b>

Debugging my App has become an issue. My application is still in development stages. My code is very neat. And yet it won't debug. Even if i run the emulator, it'll connect to the emulator but it still won't debug. I expect that when i run my code, it'll display on the emuulator given that there are no problems detected in the workspace.

Extension version: 0.0.7
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (3.61GB free)|
|Process Argv|--crash-reporter-id 8b68b6f2-b66c-428d-a69e-53ea2e57bbb3|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Dannark** [comment]
This extension is only responsible to launch the emulator, not attach your code or debugging purpose. You should check that in your environment depending on what framework you are using for example Flutter, React Native, Java/Kotlin...
